listener {
    timeout = 300                                 # 5 minutes
    lock_cmd = pidof hyprlock || hyprlock      # Avoids starting multiple instances
}

# (Optional) Lock the screen right before the system goes to sleep
listener {
    timeout = 0
    on-timeout = loginctl lock-session
}


general {
    lock_cmd = pidof hyprlock || hyprlock      # Avoids starting multiple instances
}

